### ISSUE TITLE
Displaying Harvest and Population value

### ISSUE THREAD

**Issue by NC25** [NC25/gym_fishing#1]
When I use the helper function
`def_evaluate()`
I want it to also list the harvest value and population draw for every iteration. That way I know exactly how the model is acting and then use Optuna to tune it.
Right now the model only lists the mean value reward value, which will not provide substantial help for improvement.

`def evaluate(model, num_episodes=100):
    

    env = model.get_env()
    all_episode_rewards = []
    for i in range(num_episodes):
        episode_rewards = []
        done = False
        obs = env.reset()
        while not done:
            action, _states = model.predict(obs)
            obs, reward, done, info = env.step(action)
            episode_rewards.append(reward)

        all_episode_rewards.append(sum(episode_rewards))

    mean_episode_reward = np.mean(all_episode_rewards)
    print("Mean reward:", mean_episode_reward, "Num episodes:", num_episodes)

    return mean_episode_reward #mean reward for the last episode

    mean_reward_before_train = evaluate(model, num_episodes=100)`

**Comment by cboettig** [comment]
the harvest basically is the action in the `v1` case.  in `v0` the harvest is available in the env, as is the state in both cases.

**Comment by NC25** [comment]
Isn't population draw also an action? Regarding the issue, I wanted to harvest draw and action draw to be printed during every episode or iteration. So I made a new branch just to see how the actions and obs would look like with training.
```
#Training
model = env = gym.make('fishing-v1')
model = SAC(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=50, log_interval=10)
model.save("fishing-v1")
model = SAC.load('fishing-v1')

model = SAC(MlpPolicy, env, verbose=1)
obs = env.reset()
for i in range(10):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    print("harvest: " + str(action) + "\n" + "obs: " + str(obs) + "\n" + str(rewards) + "\n" + str(dones) + "\n" + str(info))
```

You can go to the actual branch here: https://github.com/NC25/gym_fishing/blob/action-display/action_display.ipynb.
When the loop asks to print all the actions and observations, the output looks incorrect: 

```
Loading a model without an environment, this model cannot be trained until it has a valid environment.
harvest: [0.92878664]
obs: [0.]
0.75
True
{}
harvest: [1.]
obs: [0.]
0.0
True
{}
harvest: [1.]
obs: [0.]
0.0
True
```

**Comment by NC25** [comment]
The training gives an output of this
```
--------------------------------------

| current_lr              | 0.0003   |
| episodes                | 10       |
| fps                     | 5963     |
| mean 100 episode reward | 0.8      |
| n_updates               | 0        |
| time_elapsed            | 0        |
| total timesteps         | 13       |
--------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| episodes                | 20       |
| fps                     | 3665     |
| mean 100 episode reward | 0.8      |
| n_updates               | 0        |
| time_elapsed            | 0        |
| total timesteps         | 30       |
--------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| episodes                | 30       |
| fps                     | 3439     |
| mean 100 episode reward | 0.8      |
| n_updates               | 0        |
| time_elapsed            | 0        |
| total timesteps         | 45       |
--------------------------------------

```

I was thinking I could add the action and obs to the values listed above. How would I do that? I thought of changing the method of the actual Stable Baselines class to include action and obs in the output, but I don't know how to do that.
